version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sec-admin
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx
    networks:
      - admin-network

  nginx:
    image: nginx:alpine
    container_name: admin-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot-var:/var/www/certbot
    depends_on:
      - admin
    restart: unless-stopped
    networks:
      - admin-network

  certbot:
    image: certbot/certbot
    container_name: admin-certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot-var:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; 
      while :; do 
        sleep 12h & wait $${!}; 
        certbot renew --webroot -w /var/www/certbot; 
      done'
    networks:
      - admin-network

volumes:
  certbot-var:

networks:
  admin-network:
    driver: bridge
